[versions]
kotlin = "1.9.20"
publish = "1.1.0"
kotlinx-serialization = "1.6.0"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "publish" }