[versions]
kotlin = "1.9.20"
publish = "1.2.1"
kotlinx-serialization = "1.6.1"
sheetHappens = "0.5.6"
detekt = "1.23.3"
ktlintGradle = "11.6.1"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
sheetHappens = { id = "app.futured.sheethappens", version.ref = "sheetHappens" }